/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.creinig.kata;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

class LibraryTest {
  @Test
  void someLibraryMethodReturnsTrue() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
